server:
  port: 5000
line.bot:
  channel-token: 'Put Your Channel Token Here.'
  channel-secret: 'Put Your Channel Secret Here.'
  handler.path: /callback
s3:
  mp3BucketName: youtube-converted-mp3
  mp3BucketRegion: ap-southeast-1
logging:
  level:
    org.apache.http.wire: INFO